// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web3_kaypic.Data;

#nullable disable

namespace web3_kaypic.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251213185548_role")]
    partial class role
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("TRole", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("TRoleClaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TUserClaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("TUserLogin", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("TUserRole", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("TUserToken", (string)null);
                });

            modelBuilder.Entity("TMessagingChatPersonaMessage", b =>
                {
                    b.Property<long>("mcpm_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("mcpm_id"));

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("edited_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("mc_id")
                        .HasColumnType("int");

                    b.Property<int>("mcp_id")
                        .HasColumnType("int");

                    b.Property<string>("mcpm_message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("reply_to_id")
                        .HasColumnType("bigint");

                    b.Property<int>("ts_id")
                        .HasColumnType("int");

                    b.HasKey("mcpm_id");

                    b.HasIndex("mc_id");

                    b.HasIndex("mcp_id");

                    b.HasIndex("reply_to_id");

                    b.HasIndex("ts_id");

                    b.ToTable("TMessagingChatPersonaMessage", (string)null);
                });

            modelBuilder.Entity("TMessagingMedia", b =>
                {
                    b.Property<int>("mcm_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("mcm_id"));

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("created_by_mp_id")
                        .HasColumnType("int");

                    b.Property<int>("mc_id")
                        .HasColumnType("int");

                    b.Property<string>("mcm_media_category")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("mcm_url")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("ts_id")
                        .HasColumnType("int");

                    b.HasKey("mcm_id");

                    b.HasIndex("created_by_mp_id");

                    b.HasIndex("mc_id");

                    b.HasIndex("ts_id");

                    b.ToTable("TMessagingMedia", (string)null);
                });

            modelBuilder.Entity("Web3_kaypic.Models.Inscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfirmerMotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Courriel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Inscription");
                });

            modelBuilder.Entity("Web3_kaypic.Models.TMessagingChat", b =>
                {
                    b.Property<int>("mc_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("mc_id"));

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("created_by_mp_id")
                        .HasColumnType("int");

                    b.Property<string>("mc_status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("active");

                    b.Property<string>("mc_title")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("ts_id")
                        .HasColumnType("int");

                    b.HasKey("mc_id");

                    b.HasIndex("created_by_mp_id");

                    b.HasIndex("ts_id");

                    b.ToTable("TMessagingChat", (string)null);
                });

            modelBuilder.Entity("Web3_kaypic.Models.TMessagingChatPersona", b =>
                {
                    b.Property<int>("mcp_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("mcp_id"));

                    b.Property<DateTime>("added_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("mc_id")
                        .HasColumnType("int");

                    b.Property<string>("mcp_status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("mp_id")
                        .HasColumnType("int");

                    b.Property<int>("ts_id")
                        .HasColumnType("int");

                    b.HasKey("mcp_id");

                    b.HasIndex("mc_id");

                    b.HasIndex("mp_id");

                    b.HasIndex("ts_id");

                    b.ToTable("TMessagingChatPersona");
                });

            modelBuilder.Entity("Web3_kaypic.Models.TMessagingPersona", b =>
                {
                    b.Property<int>("mp_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("mp_id"));

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("mp_category")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("mp_email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("mp_fname")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("mp_lname")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("mp_status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("char(2)")
                        .HasDefaultValue("ac");

                    b.Property<int>("ts_id")
                        .HasColumnType("int");

                    b.HasKey("mp_id");

                    b.HasIndex("mp_email")
                        .IsUnique();

                    b.HasIndex("ts_id");

                    b.ToTable("TMessagingPersona", (string)null);
                });

            modelBuilder.Entity("Web3_kaypic.Models.TNews", b =>
                {
                    b.Property<int>("news_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("news_id"));

                    b.Property<int>("news_author_mp_id")
                        .HasColumnType("int");

                    b.Property<string>("news_body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("news_date_end")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("news_date_posted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("news_date_start")
                        .HasColumnType("datetime2");

                    b.Property<string>("news_media_category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("n");

                    b.Property<string>("news_media_url")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("news_status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("active");

                    b.Property<string>("news_title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("ts_id")
                        .HasColumnType("int");

                    b.HasKey("news_id");

                    b.HasIndex("news_author_mp_id");

                    b.HasIndex("ts_id");

                    b.ToTable("TNews", (string)null);
                });

            modelBuilder.Entity("Web3_kaypic.Models.TPlayer", b =>
                {
                    b.Property<int>("player_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("player_id"));

                    b.Property<int>("IdSaison")
                        .HasColumnType("int");

                    b.Property<int?>("PersonneMessageriemp_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("player_email")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("player_fname")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("player_guardian_email")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("player_guardian_fname")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("player_guardian_lname")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("player_lname")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("statut")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("player_id");

                    b.HasIndex("IdSaison");

                    b.HasIndex("PersonneMessageriemp_id");

                    b.ToTable("TPlayer", (string)null);
                });

            modelBuilder.Entity("Web3_kaypic.Models.TTeamManager", b =>
                {
                    b.Property<int>("tm_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tm_id"));

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("tm_email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("tm_fname")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("tm_lname")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("tm_id");

                    b.HasIndex("tm_email")
                        .IsUnique();

                    b.ToTable("TTeamManager", (string)null);
                });

            modelBuilder.Entity("Web3_kaypic.Models.TTeamSeason", b =>
                {
                    b.Property<int>("ts_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ts_id"));

                    b.Property<int?>("TTeamManagertm_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ts_chat_key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ts_name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ts_status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("char(2)")
                        .HasDefaultValue("ac");

                    b.HasKey("ts_id");

                    b.HasIndex("TTeamManagertm_id");

                    b.HasIndex("ts_chat_key")
                        .IsUnique();

                    b.ToTable("TTeamSeason", (string)null);
                });

            modelBuilder.Entity("web3_kaypic.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("TUser", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("web3_kaypic.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("web3_kaypic.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("web3_kaypic.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("web3_kaypic.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TMessagingChatPersonaMessage", b =>
                {
                    b.HasOne("Web3_kaypic.Models.TMessagingChat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("mc_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Web3_kaypic.Models.TMessagingChatPersona", "ChatPersona")
                        .WithMany("Messages")
                        .HasForeignKey("mcp_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TMessagingChatPersonaMessage", "ReplyToMessage")
                        .WithMany("Replies")
                        .HasForeignKey("reply_to_id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Web3_kaypic.Models.TTeamSeason", "TeamSeason")
                        .WithMany("ChatMessages")
                        .HasForeignKey("ts_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("ChatPersona");

                    b.Navigation("ReplyToMessage");

                    b.Navigation("TeamSeason");
                });

            modelBuilder.Entity("TMessagingMedia", b =>
                {
                    b.HasOne("Web3_kaypic.Models.TMessagingPersona", "Creator")
                        .WithMany("Medias")
                        .HasForeignKey("created_by_mp_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Web3_kaypic.Models.TMessagingChat", "MessagingChat")
                        .WithMany("Medias")
                        .HasForeignKey("mc_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web3_kaypic.Models.TTeamSeason", "TeamSeason")
                        .WithMany("Medias")
                        .HasForeignKey("ts_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("MessagingChat");

                    b.Navigation("TeamSeason");
                });

            modelBuilder.Entity("Web3_kaypic.Models.TMessagingChat", b =>
                {
                    b.HasOne("Web3_kaypic.Models.TMessagingPersona", "CreatedBy")
                        .WithMany("CreatedChats")
                        .HasForeignKey("created_by_mp_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Web3_kaypic.Models.TTeamSeason", "TeamSeason")
                        .WithMany("Chats")
                        .HasForeignKey("ts_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("TeamSeason");
                });

            modelBuilder.Entity("Web3_kaypic.Models.TMessagingChatPersona", b =>
                {
                    b.HasOne("Web3_kaypic.Models.TMessagingChat", "Chat")
                        .WithMany("ChatPersonas")
                        .HasForeignKey("mc_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web3_kaypic.Models.TMessagingPersona", "Persona")
                        .WithMany("ChatPersonas")
                        .HasForeignKey("mp_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Web3_kaypic.Models.TTeamSeason", "TeamSeason")
                        .WithMany("ChatPersonas")
                        .HasForeignKey("ts_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Persona");

                    b.Navigation("TeamSeason");
                });

            modelBuilder.Entity("Web3_kaypic.Models.TMessagingPersona", b =>
                {
                    b.HasOne("Web3_kaypic.Models.TTeamSeason", "TeamSeason")
                        .WithMany("Personas")
                        .HasForeignKey("ts_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamSeason");
                });

            modelBuilder.Entity("Web3_kaypic.Models.TNews", b =>
                {
                    b.HasOne("Web3_kaypic.Models.TMessagingPersona", "AuthorPersona")
                        .WithMany("AuthoredNews")
                        .HasForeignKey("news_author_mp_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Web3_kaypic.Models.TTeamSeason", "TeamSeason")
                        .WithMany("News")
                        .HasForeignKey("ts_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorPersona");

                    b.Navigation("TeamSeason");
                });

            modelBuilder.Entity("Web3_kaypic.Models.TPlayer", b =>
                {
                    b.HasOne("Web3_kaypic.Models.TTeamSeason", "SaisonEquipe")
                        .WithMany()
                        .HasForeignKey("IdSaison")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web3_kaypic.Models.TMessagingPersona", "PersonneMessagerie")
                        .WithMany()
                        .HasForeignKey("PersonneMessageriemp_id");

                    b.Navigation("PersonneMessagerie");

                    b.Navigation("SaisonEquipe");
                });

            modelBuilder.Entity("Web3_kaypic.Models.TTeamSeason", b =>
                {
                    b.HasOne("Web3_kaypic.Models.TTeamManager", null)
                        .WithMany("SaisonEquipes")
                        .HasForeignKey("TTeamManagertm_id");
                });

            modelBuilder.Entity("TMessagingChatPersonaMessage", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Web3_kaypic.Models.TMessagingChat", b =>
                {
                    b.Navigation("ChatPersonas");

                    b.Navigation("Medias");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Web3_kaypic.Models.TMessagingChatPersona", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Web3_kaypic.Models.TMessagingPersona", b =>
                {
                    b.Navigation("AuthoredNews");

                    b.Navigation("ChatPersonas");

                    b.Navigation("CreatedChats");

                    b.Navigation("Medias");
                });

            modelBuilder.Entity("Web3_kaypic.Models.TTeamManager", b =>
                {
                    b.Navigation("SaisonEquipes");
                });

            modelBuilder.Entity("Web3_kaypic.Models.TTeamSeason", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("ChatPersonas");

                    b.Navigation("Chats");

                    b.Navigation("Medias");

                    b.Navigation("News");

                    b.Navigation("Personas");
                });
#pragma warning restore 612, 618
        }
    }
}
